// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails application service. All exported methods are bound to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActiveTarget returns the id of the target currently in use for repoPath, or
 * the empty string when none is detected.
 */
export function ActiveTarget(repoPath: string): $CancellablePromise<string> {
    return $Call.ByID(2394438090, repoPath);
}

/**
 * AddSkillSource adds or updates a global skill source (git URL or local folder).
 */
export function AddSkillSource(alias: string, url: string): $CancellablePromise<void> {
    return $Call.ByID(2803609340, alias, url);
}

/**
 * AuditLogPath returns the platform-correct path to ~/.skell/audit.log.
 */
export function AuditLogPath(): $CancellablePromise<string> {
    return $Call.ByID(3629702033);
}

/**
 * ContributeMetadata creates a GitHub PR to improve the metadata of a skill.
 * It relies on an existing GitHub CLI login and only forks when the current
 * account cannot push a branch to the upstream repository.
 */
export function ContributeMetadata(params: $models.ContributeParams): $CancellablePromise<$models.ContributeResult> {
    return $Call.ByID(1008264935, params);
}

/**
 * DetectTargets returns the platform(s) already present in repoPath. A target
 * is reported as "detected" when its directory contains either skell.toml or a
 * skills/ subdirectory.
 */
export function DetectTargets(repoPath: string): $CancellablePromise<$models.AgentTarget[] | null> {
    return $Call.ByID(2920689880, repoPath);
}

/**
 * GlobalRootDir returns the global Skell root directory (~/.skell) and ensures
 * the global manifest exists so that `skell search --repo <path>` can resolve it.
 */
export function GlobalRootDir(): $CancellablePromise<string> {
    return $Call.ByID(2693605881);
}

/**
 * IsRepoInitialized returns true when the given directory contains a Skell
 * manifest in any supported AI-agent layout (.claude, .codex, .github, .cursor),
 * meaning `skell init` has already been run for some target.
 */
export function IsRepoInitialized(repoPath: string): $CancellablePromise<boolean> {
    return $Call.ByID(3848862957, repoPath);
}

/**
 * ListDirectory returns the immediate children of a directory.
 */
export function ListDirectory(path: string): $CancellablePromise<$models.FileEntry[] | null> {
    return $Call.ByID(3882022436, path);
}

/**
 * ListSkillSources returns the globally configured skill sources from ~/.skell/config.toml.
 */
export function ListSkillSources(): $CancellablePromise<$models.SkillSource[] | null> {
    return $Call.ByID(3339277332);
}

/**
 * PreviewRegistrySkill returns the SKILL.md contents and disk path for a skill
 * in a (cached or local-folder) registry, without installing it. Used by the
 * Discover Skills preview modal.
 */
export function PreviewRegistrySkill(registryAlias: string, registryURL: string, skillName: string): $CancellablePromise<$models.SkillPreview> {
    return $Call.ByID(3669316229, registryAlias, registryURL, skillName);
}

/**
 * ReadFileContent reads and returns the contents of a file.
 */
export function ReadFileContent(path: string): $CancellablePromise<string> {
    return $Call.ByID(2440131916, path);
}

/**
 * ReadSkillMetadata parses the SKILL.md in the given directory and returns
 * the editable metadata fields.
 */
export function ReadSkillMetadata(installedPath: string): $CancellablePromise<$models.SkillMetadataFields> {
    return $Call.ByID(2621935323, installedPath);
}

/**
 * RemoveSkillSource removes a global skill source by alias.
 */
export function RemoveSkillSource(alias: string): $CancellablePromise<void> {
    return $Call.ByID(2166783643, alias);
}

/**
 * ResolveSkillSourceRepoURL tries to upgrade a repo-root source URL into the
 * nested skill folder URL by consulting the local registry cache.
 */
export function ResolveSkillSourceRepoURL(sourceRepo: string, registryAlias: string, skillName: string): $CancellablePromise<string> {
    return $Call.ByID(1846080558, sourceRepo, registryAlias, skillName);
}

export function RunSkell(args: string[] | null): $CancellablePromise<$models.SkellResult> {
    return $Call.ByID(2394374327, args);
}

/**
 * SelectDirectory opens a native directory picker dialog and returns the selected path.
 */
export function SelectDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1735672136);
}

/**
 * SkellPresent returns true if a usable skell binary can be resolved.
 * The GUI uses this (and catches the not-found error from RunSkell) to show
 * friendly "install the CLI first" guidance instead of generic errors or
 * perpetual spinners on brand-new machines (where only the GUI is installed).
 */
export function SkellPresent(): $CancellablePromise<boolean> {
    return $Call.ByID(2004525469);
}

/**
 * SkellVersion returns the output of `skell --version`.
 */
export function SkellVersion(): $CancellablePromise<string> {
    return $Call.ByID(3500197102);
}

/**
 * SupportedTargets returns the static list of platforms the GUI offers as
 * choices in the init dialog.
 */
export function SupportedTargets(): $CancellablePromise<$models.AgentTarget[] | null> {
    return $Call.ByID(1734000213);
}

/**
 * ValidateSkill runs `skell validate` for one skill (or all skills when
 * skillName is empty) in repoPath and returns the parsed results. When full is
 * true, offline content and contamination analysis are included. Results are
 * returned even when validation reports errors (a non-zero CLI exit).
 */
export function ValidateSkill(repoPath: string, skillName: string, full: boolean): $CancellablePromise<$models.SkillValidationResult[] | null> {
    return $Call.ByID(567263264, repoPath, skillName, full);
}
