// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentTarget describes a supported AI-agent platform layout for the GUI.
 */
export interface AgentTarget {
    "id": string;
    "displayName": string;
    "dir": string;
    "detected": boolean;
}

/**
 * ContributeParams describes a metadata-contribution PR request.
 */
export interface ContributeParams {
    "installedPath": string;
    "sourceRepo": string;
    "skillName": string;
    "metadata": SkillMetadataFields;
}

/**
 * ContributeResult is returned after attempting to open a PR.
 */
export interface ContributeResult {
    "prUrl": string;
    "success": boolean;
    "error"?: string;
}

/**
 * FileEntry represents a filesystem entry (file or directory).
 */
export interface FileEntry {
    "name": string;
    "is_dir": boolean;
    "path": string;
}

/**
 * SkellResult is the JSON-shaped result returned to the frontend for skell invocations.
 */
export interface SkellResult {
    "stdout": string;
    "stderr": string;
    "success": boolean;
}

/**
 * SkillAnalysis holds the offline quality metrics surfaced to the GUI (mirrors
 * internal/validator.Analysis). Nil when only structure checks ran.
 */
export interface SkillAnalysis {
    "word_count": number;
    "code_block_ratio": number;
    "imperative_ratio": number;
    "information_density": number;
    "instruction_specificity": number;
    "section_count": number;
    "list_item_count": number;
    "has_content": boolean;
    "contamination_score": number;
    "contamination_level": string;
    "code_languages": string[] | null;
    "mismatched_categories": string[] | null;
    "language_mismatch": boolean;
    "has_contamination": boolean;
    "total_tokens": number;
    "skill_tokens": number;
}

/**
 * SkillMetadataFields holds the user-editable subset of SKILL.md frontmatter.
 */
export interface SkillMetadataFields {
    "description": string;
    "tags": string;
    "lifecycle": string;
    "owner": string;
    "version": string;
}

/**
 * SkillPreview describes a not-yet-installed skill: its SKILL.md content and
 * the on-disk location it was read from. Found is false when the registry
 * cache hasn't been populated yet — the caller can still render the metadata
 * it already has from the registry listing.
 */
export interface SkillPreview {
    "readme_content": string;
    "source_path": string;
    "source_url": string;
    "source_type": string;
    "found": boolean;
}

/**
 * SkillSource represents a persistent skill source (git or local folder).
 */
export interface SkillSource {
    "alias": string;
    "url": string;
    "is_local": boolean;
}

/**
 * SkillValidationFinding mirrors one validator finding for the frontend.
 */
export interface SkillValidationFinding {
    "severity": string;
    "category": string;
    "message": string;
    "file": string;
    "line": number;
}

/**
 * SkillValidationResult is the per-skill validation outcome surfaced to the GUI.
 */
export interface SkillValidationResult {
    "name": string;
    "errors": number;
    "warnings": number;
    "findings": SkillValidationFinding[] | null;
    "analysis"?: SkillAnalysis | null;
}
